name: "Push to cache"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: usdogu
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix build github:srid/devour-flake -L --no-link --print-out-paths --override-input flake . | xargs cat | cachix push usdogu
